"""Stage 3: Score Ward departures (programmatic)."""

from __future__ import annotations

import json
import logging
import time
from pathlib import Path

from tqdm import tqdm

from alienbench.config import load_config
from alienbench.dimensions import compute_ward_score
from alienbench.paths import (
    iter_extractions,
    load_scored_ids,
    ward_scores_path,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run(
    config_path: str = "config.yaml",
    human_models: list[str] | None = None,
) -> None:
    """Score Ward departures for all subject models and any pre-collected human models.

    ``human_models`` lists model keys whose extraction records are provided
    externally (e.g. ``["human/prolific-baseline"]``). They are appended to
    ``cfg.models`` for scoring but are not generated by Stage 1. Pass
    ``None`` (default) to process only the models in ``config.yaml``.
    """
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    cfg = load_config(config_path)
    data_dir = Path(cfg.data_dir)
    # human_models are pre-collected external responses; they extend cfg.models
    # without being generated by Stage 1.
    models_to_process = list(cfg.models) + list(human_models or [])

    ward_tasks = []

    for judge in cfg.judge_models:
        for model in models_to_process:
            for variant in cfg.prompt_variants:
                extractions = list(iter_extractions(data_dir, judge, model, variant.id))
                if not extractions:
                    continue

                w_path = ward_scores_path(data_dir, judge, model, variant.id)
                done_ward = load_scored_ids(w_path)
                pending_ward = [e for e in extractions if e["generation_id"] not in done_ward]
                if pending_ward:
                    ward_tasks.append((judge, model, variant.id, w_path, pending_ward))

    if not ward_tasks:
        logger.info("All scoring already complete.")
        return

    total_ward = sum(len(p) for _, _, _, _, p in ward_tasks)
    logger.info("Computing Ward scores for %d records", total_ward)
    n_scored = 0
    n_skipped = 0
    with tqdm(total=total_ward, desc="Ward scoring", unit="record") as bar:
        for judge, model, prompt_id, w_path, pending in ward_tasks:
            w_path.parent.mkdir(parents=True, exist_ok=True)
            with open(w_path, "a") as f:
                for extraction in pending:
                    try:
                        ward = compute_ward_score(extraction["features"])
                        record = {
                            "generation_id": extraction["generation_id"],
                            "judge_model": judge,
                            "judge_model_resolved": extraction.get("judge_model_resolved"),
                            "judge_call_id": extraction.get("judge_call_id"),
                            "subject_model": model,
                            "prompt_variant": prompt_id,
                            "ward_score": ward["total"],
                            "per_dimension": ward["per_dimension"],
                            "timestamp": time.time(),
                        }
                        f.write(json.dumps(record) + "\n")
                        f.flush()
                        n_scored += 1
                    except (KeyError, TypeError, AttributeError) as e:
                        # Defence-in-depth: parse_features in extract.py now
                        # rejects malformed inner structure, but if a record
                        # ever slips through (legacy data, manual edit, future
                        # schema drift) we log and skip rather than abort the
                        # whole stage.
                        logger.error(
                            "Could not score extraction %s by %s: %s. Skipping.",
                            extraction.get("generation_id"), judge, e,
                        )
                        n_skipped += 1
                    bar.update(1)

    if n_skipped > 0:
        logger.error("Scoring complete: %d scored, %d skipped due to malformed extractions.", n_scored, n_skipped)
    else:
        logger.info("Scoring complete: %d/%d records scored.", n_scored, n_scored)
